[project]
authors = ["Samuel Ibarra <ing.samuelibarra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Advent of code problem solving"
name = "mojo"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = {cmd = "mojo test -I src src"}
app = {cmd = "mojo run src/main.mojo"}

[dependencies]
max = ">=24.6.0.dev2024092405,<25"
