[project]
name = "mojo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Samuel Ibarra <ing.samuelibarra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
